package com.sandbox.MeetingScheduler.data;

// Generated 9-Jul-2015 9:53:10 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AvailabilityPeriod generated by hbm2java
 */
@Entity
@Table(name = "availability_period", catalog = "msdb")
public class AvailabilityPeriod implements java.io.Serializable {

	private Integer avPId;
	private Set<Attendant> attendants = new HashSet<Attendant>(0);
	private Set<Location> locations = new HashSet<Location>(0);
	private Set<Meeting> meetings = new HashSet<Meeting>(0);
	private Set<Availability> availabilities = new HashSet<Availability>(0);

	public AvailabilityPeriod() {
	}

	public AvailabilityPeriod(Set<Attendant> attendants,
			Set<Location> locations, Set<Meeting> meetings,
			Set<Availability> availabilities) {
		this.attendants = attendants;
		this.locations = locations;
		this.meetings = meetings;
		this.availabilities = availabilities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "av_p_id", unique = true, nullable = false)
	public Integer getAvPId() {
		return this.avPId;
	}

	public void setAvPId(Integer avPId) {
		this.avPId = avPId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "availabilityPeriod")
	public Set<Attendant> getAttendants() {
		return this.attendants;
	}

	public void setAttendants(Set<Attendant> attendants) {
		this.attendants = attendants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "availabilityPeriod")
	public Set<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<Location> locations) {
		this.locations = locations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "availabilityPeriod")
	public Set<Meeting> getMeetings() {
		return this.meetings;
	}

	public void setMeetings(Set<Meeting> meetings) {
		this.meetings = meetings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "availabilityPeriod")
	public Set<Availability> getAvailabilities() {
		return this.availabilities;
	}

	public void setAvailabilities(Set<Availability> availabilities) {
		this.availabilities = availabilities;
	}

}
