package com.sandbox.MeetingScheduler.data;

// Generated 9-Jul-2015 9:53:10 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "msdb")
public class Location implements java.io.Serializable {

	private Integer locationId;
	private AvailabilityPeriod availabilityPeriod;
	private String locName;
	private Set<Attendant> attendants = new HashSet<Attendant>(0);

	public Location() {
	}

	public Location(AvailabilityPeriod availabilityPeriod, String locName,
			Set<Attendant> attendants) {
		this.availabilityPeriod = availabilityPeriod;
		this.locName = locName;
		this.attendants = attendants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "location_id", unique = true, nullable = false)
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_av_p_id")
	public AvailabilityPeriod getAvailabilityPeriod() {
		return this.availabilityPeriod;
	}

	public void setAvailabilityPeriod(AvailabilityPeriod availabilityPeriod) {
		this.availabilityPeriod = availabilityPeriod;
	}

	@Column(name = "loc_name")
	public String getLocName() {
		return this.locName;
	}

	public void setLocName(String locName) {
		this.locName = locName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<Attendant> getAttendants() {
		return this.attendants;
	}

	public void setAttendants(Set<Attendant> attendants) {
		this.attendants = attendants;
	}

}
