package com.sandbox.MeetingScheduler.data;

// Generated 9-Jul-2015 9:53:10 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Meeting generated by hbm2java
 */
@Entity
@Table(name = "meeting", catalog = "msdb")
public class Meeting implements java.io.Serializable {

	private Integer meetingId;
	private AvailabilityPeriod availabilityPeriod;
	private String meetingName;
	private Boolean cancelledInd;
	private Set<Attendant> attendants = new HashSet<Attendant>(0);

	public Meeting() {
	}

	public Meeting(AvailabilityPeriod availabilityPeriod, String meetingName,
			Boolean cancelledInd, Set<Attendant> attendants) {
		this.availabilityPeriod = availabilityPeriod;
		this.meetingName = meetingName;
		this.cancelledInd = cancelledInd;
		this.attendants = attendants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "meeting_id", unique = true, nullable = false)
	public Integer getMeetingId() {
		return this.meetingId;
	}

	public void setMeetingId(Integer meetingId) {
		this.meetingId = meetingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_av_p_id")
	public AvailabilityPeriod getAvailabilityPeriod() {
		return this.availabilityPeriod;
	}

	public void setAvailabilityPeriod(AvailabilityPeriod availabilityPeriod) {
		this.availabilityPeriod = availabilityPeriod;
	}

	@Column(name = "meeting_name")
	public String getMeetingName() {
		return this.meetingName;
	}

	public void setMeetingName(String meetingName) {
		this.meetingName = meetingName;
	}

	@Column(name = "cancelled_ind")
	public Boolean getCancelledInd() {
		return this.cancelledInd;
	}

	public void setCancelledInd(Boolean cancelledInd) {
		this.cancelledInd = cancelledInd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "meeting")
	public Set<Attendant> getAttendants() {
		return this.attendants;
	}

	public void setAttendants(Set<Attendant> attendants) {
		this.attendants = attendants;
	}

}
