package com.sandbox.MeetingScheduler.data;

// Generated 9-Jul-2015 9:53:10 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserTbl generated by hbm2java
 */
@Entity
@Table(name = "user_tbl")
public class UserTbl implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String pass;
	private String email;

	public UserTbl() {
	}

	public UserTbl(String userName, String pass, String email) {
		this.userName = userName;
		this.pass = pass;
		this.email = email;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "pass")
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "UserTbl [userId=" + userId + ", userName=" + userName
				+ ", pass=" + pass + ", email=" + email + "]";
	}

}
