package com.sandbox.MeetingScheduler.data;

// Generated 9-Jul-2015 9:53:10 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attendant generated by hbm2java
 */
@Entity
@Table(name = "attendant", catalog = "msdb")
public class Attendant implements java.io.Serializable {

	private int attendantId;
	private AvailabilityPeriod availabilityPeriod;
	private Location location;
	private Meeting meeting;
	private UserTbl userTbl;
	private Boolean isImportant;

	public Attendant() {
	}

	public Attendant(int attendantId) {
		this.attendantId = attendantId;
	}

	public Attendant(int attendantId, AvailabilityPeriod availabilityPeriod,
			Location location, Meeting meeting, UserTbl userTbl,
			Boolean isImportant) {
		this.attendantId = attendantId;
		this.availabilityPeriod = availabilityPeriod;
		this.location = location;
		this.meeting = meeting;
		this.userTbl = userTbl;
		this.isImportant = isImportant;
	}

	@Id
	@Column(name = "attendant_id", unique = true, nullable = false)
	public int getAttendantId() {
		return this.attendantId;
	}

	public void setAttendantId(int attendantId) {
		this.attendantId = attendantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attendant_av_p_id")
	public AvailabilityPeriod getAvailabilityPeriod() {
		return this.availabilityPeriod;
	}

	public void setAvailabilityPeriod(AvailabilityPeriod availabilityPeriod) {
		this.availabilityPeriod = availabilityPeriod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "preferred_location")
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_id")
	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public UserTbl getUserTbl() {
		return this.userTbl;
	}

	public void setUserTbl(UserTbl userTbl) {
		this.userTbl = userTbl;
	}

	@Column(name = "is_important")
	public Boolean getIsImportant() {
		return this.isImportant;
	}

	public void setIsImportant(Boolean isImportant) {
		this.isImportant = isImportant;
	}

}
