package com.sandbox.MeetingScheduler.data;

// Generated 9-Jul-2015 9:53:10 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Availability generated by hbm2java
 */
@Entity
@Table(name = "availability")
public class Availability implements java.io.Serializable {

	private Integer avId;
	private AvailabilityPeriod availabilityPeriod;
	private Date startDt;
	private Date endDt;
	private Boolean isAvailable;
	private Integer preference;

	public Availability() {
	}

	public Availability(AvailabilityPeriod availabilityPeriod, Date startDt,
			Date endDt, Boolean isAvailable, Integer preference) {
		this.availabilityPeriod = availabilityPeriod;
		this.startDt = startDt;
		this.endDt = endDt;
		this.isAvailable = isAvailable;
		this.preference = preference;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "av_id", unique = true, nullable = false)
	public Integer getAvId() {
		return this.avId;
	}

	public void setAvId(Integer avId) {
		this.avId = avId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "av_p_id")
	public AvailabilityPeriod getAvailabilityPeriod() {
		return this.availabilityPeriod;
	}

	public void setAvailabilityPeriod(AvailabilityPeriod availabilityPeriod) {
		this.availabilityPeriod = availabilityPeriod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_dt", length = 10)
	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_dt", length = 10)
	public Date getEndDt() {
		return this.endDt;
	}

	public void setEndDt(Date endDt) {
		this.endDt = endDt;
	}

	@Column(name = "is_available")
	public Boolean getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	@Column(name = "preference")
	public Integer getPreference() {
		return this.preference;
	}

	public void setPreference(Integer preference) {
		this.preference = preference;
	}

}
