//package com.sandbox.MeetingScheduler.data;
//
//// Generated 9-Jul-2015 9:53:10 AM by Hibernate Tools 4.3.1
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.Id;
//import javax.persistence.Table;
//
///**
// * Param generated by hbm2java
// */
//@Entity
//@Table(name = "param", catalog = "msdb")
//public class Param implements java.io.Serializable {
//
//	private String name;
//	private String value;
//
//	public Param() {
//	}
//
//	public Param(String name) {
//		this.name = name;
//	}
//
//	public Param(String name, String value) {
//		this.name = name;
//		this.value = value;
//	}
//
//	@Id
//	@Column(name = "name", unique = true, nullable = false, length = 45)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "value")
//	public String getValue() {
//		return this.value;
//	}
//
//	public void setValue(String value) {
//		this.value = value;
//	}
//
//}
